import type { CompanyProfile, PayslipTemplate } from "@/validations/system";

export const DEFAULT_COMPANY_PROFILE: CompanyProfile = {
  name: "ethelius",
  legalName: "Ethelius Technologies Private Limited",
  address: "Tech Park, Ring Road, Surat, Gujarat 395007",
  email: "payroll@ethelius.com",
  phone: "+91 98765 43210",
  regNo: "CIN U72900GJ2019PTC000000",
  website: "ethelius.com",
};

/** Defaults reproduce the approved payslip design exactly. */
export const DEFAULT_PAYSLIP_TEMPLATE: PayslipTemplate = {
  accent: "#0B6B52",
  mint: "#B8F3E5",
  ink: "#0E1A16",
  showAttendance: true,
  showStatutory: true,
  showBank: true,
  maskAccount: true,
  showSignature: true,
  signedBy: "For ethelius — authorised signatory",
  footerNote: "This slip is generated by the payroll system and is valid without a signature. Keep it for your records.",
  numberPrefix: "PAY",
};

export const SETTING_KEYS = {
  companyProfile: "company.profile",
  payslipTemplate: "payslip.template",
  companyLogo: "company.logo",
  signatureImage: "payslip.signature",
  lastScheduledCheck: "system.lastScheduledCheck",
} as const;
